---
- name: Install dependencies
  yum:
    name:
      - curl
      - gnupg2
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Vector GPG key
  rpm_key:
    key: https://repositories.timber.io/public/vector/gpg.key
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Vector repository
  yum_repository:
    name: vector
    description: Vector repository
    baseurl: https://repositories.timber.io/public/vector/rpm/el/$releasever/$basearch
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install Vector
  yum:
    name: vector
    state: present
  when: ansible_os_family == "RedHat"

- name: Create Vector config directory
  file:
    path: /etc/vector
    state: directory

- name: Copy Vector config
  copy:
    content: |
      [sources.in]
      type = "stdin"
      [sinks.out]
      inputs = ["in"]
      type = "console"
    dest: /etc/vector/vector.toml
  notify: restart vector

- name: Start Vector service
  systemd:
    name: vector
    state: started
    enabled: yes
